In [1]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from model import PQRNN
from dataset import create_dataloaders,DummyDataset
model = PQRNN(b=128,d=64,output_size=6,dropout=0.5,lr=1e-3,num_layers=1,fc_sizes=[128,64],rnn_type='GRU',multilabel=True)#.load_from_checkpoint(checkpoint_path='checkpoints.ckpt',map_location=torch.device('cpu'),hparams_file='lightning_logs/default/version_0/hparams.yaml')

df = pd.read_csv('data/test.csv')
#test_dataset = DummyDataset(df[['comment_text']].to_dict('records'),has_label=False,feature_size=128*2,add_eos_tag=True,add_bos_tag=True,max_seq_len=512,label2index=None)


D:\Deep_Learning\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
D:\Deep_Learning\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
D:\Deep_Learning\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  stacklevel=1)
D:\Deep_Learning\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py:61: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


In [2]:
model

PQRNN(
  (tanh): Hardtanh(min_val=-1.0, max_val=1.0)
  (qrnn): GRU(128, 64, dropout=0.5, bidirectional=True)
  (output): ModuleList(
    (0): ReLU()
    (1): Linear(in_features=64, out_features=128, bias=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): ReLU()
    (5): Linear(in_features=64, out_features=6, bias=True)
  )
  (loss): BCEWithLogitsLoss()
)

In [31]:
df = pd.read_csv('data/train.csv')
dataloader = create_dataloaders(task='toxic',label2index=None,batch_size=32,feature_size=128*2,data_path='data')
#dataloader = create_dataloaders(test_dataset)
model.eval()
for test in dataloader:
  for batch in test:
    #projections,lengths = batch
    projections,length,label = batch
    print(torch.sigmoid(model.forward(projections)),label)
    break


tensor([[0.3298, 0.0925, 0.1864, 0.1180, 0.1912, 0.1533],
        [0.3328, 0.0969, 0.1912, 0.1229, 0.1955, 0.1586],
        [0.3232, 0.0875, 0.1793, 0.1133, 0.1848, 0.1466],
        [0.3126, 0.0811, 0.1731, 0.1060, 0.1765, 0.1395],
        [0.3369, 0.0923, 0.1814, 0.1224, 0.1964, 0.1542],
        [0.3405, 0.0997, 0.1941, 0.1261, 0.2012, 0.1612],
        [0.3818, 0.1197, 0.2128, 0.1526, 0.2369, 0.1875],
        [0.3380, 0.0961, 0.1903, 0.1221, 0.1975, 0.1572],
        [0.3269, 0.0919, 0.1858, 0.1177, 0.1896, 0.1523],
        [0.3934, 0.1267, 0.2291, 0.1537, 0.2447, 0.1936],
        [0.3408, 0.0965, 0.1938, 0.1229, 0.2003, 0.1591],
        [0.3557, 0.1052, 0.2029, 0.1317, 0.2119, 0.1689],
        [0.3579, 0.1052, 0.2012, 0.1331, 0.2130, 0.1693],
        [0.3471, 0.0993, 0.1950, 0.1266, 0.2047, 0.1631],
        [0.3354, 0.0968, 0.1912, 0.1226, 0.1961, 0.1579],
        [0.3778, 0.1208, 0.2182, 0.1490, 0.2323, 0.1861],
        [0.3828, 0.1184, 0.2153, 0.1480, 0.2346, 0.1850],
        [0.329

In [18]:
model_load = model.load_from_checkpoint('checkpoints.ckpt',map_location=torch.device('cpu'))

RuntimeError: Error(s) in loading state_dict for PQRNN:
	Missing key(s) in state_dict: "qrnn.weight_ih_l1", "qrnn.weight_hh_l1", "qrnn.bias_ih_l1", "qrnn.bias_hh_l1", "qrnn.weight_ih_l1_reverse", "qrnn.weight_hh_l1_reverse", "qrnn.bias_ih_l1_reverse", "qrnn.bias_hh_l1_reverse", "qrnn.weight_ih_l2", "qrnn.weight_hh_l2", "qrnn.bias_ih_l2", "qrnn.bias_hh_l2", "qrnn.weight_ih_l2_reverse", "qrnn.weight_hh_l2_reverse", "qrnn.bias_ih_l2_reverse", "qrnn.bias_hh_l2_reverse", "qrnn.weight_ih_l3", "qrnn.weight_hh_l3", "qrnn.bias_ih_l3", "qrnn.bias_hh_l3", "qrnn.weight_ih_l3_reverse", "qrnn.weight_hh_l3_reverse", "qrnn.bias_ih_l3_reverse", "qrnn.bias_hh_l3_reverse". 

In [15]:
import torch
from model import PQRNN
from dataset import create_dataloaders,DummyDataset
from torch.utils.data import Dataset
model = PQRNN(d=256,num_layers=2,rnn_type='GRU',multilabel=True,output_size=6).load_from_checkpoint(checkpoint_path='checkpoints-v3.ckpt',map_location=torch.device('cpu'),hparams_file='lightning_logs/default/version_0/hparams.yaml',strict=False)

In [29]:
from dataset import collate_fn
import pandas as pd
from torch.utils.data import DataLoader
df = pd.DataFrame({'text':["stupid ass modders","Fucking nigga","U dumb bitchesss"]})
test_dataset = DummyDataset(df[['text']].to_dict('records'),has_label=False,max_seq_len=128,feature_size=128*2)
dataloader = DataLoader(test_dataset,batch_size=1,collate_fn=collate_fn,num_workers=4)

In [30]:
model.eval()
for batch in dataloader:
  #print(batch[0])
  #projections,lengths = batch
  projections,length,label = batch
  print(torch.sigmoid(model.forward(projections[:,:,:])))


tensor([[0.3885, 0.2170, 0.3021, 0.2318, 0.2748, 0.2524]],
       grad_fn=<SigmoidBackward>)
tensor([[0.4354, 0.2803, 0.3554, 0.2860, 0.3300, 0.3035]],
       grad_fn=<SigmoidBackward>)
tensor([[0.4525, 0.2998, 0.3691, 0.3020, 0.3490, 0.3192]],
       grad_fn=<SigmoidBackward>)


In [ ]:
import pandas as pd 
